services:
  - type: web
    name: engineering-quality-cicd
    env: docker
    region: ohio
    plan: free
    branch: master
    rootDir: servicepulse
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
